apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-webapp
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-webapp
spec:
  hosts:
  - "*"
  gateways:
  - gateway-webapp
  http:
  - match:
    - uri:
        exact: /
    # - uri:
    #     prefix: /static
    # - uri:
    #     exact: /login
    # - uri:
    #     exact: /logout
    # - uri:
    #     prefix: /api/v1/products
    route:
    - destination:
        host: webapp
        port:
          number: 80