apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      serviceAccountName: sa-webapp
      containers:
        - env:
            - name: REACT_APP_TEST
              value: report-service
            - name: REACT_APP_THEME
              value: light
          name: webapp
          image: docker.io/cmwylie19/listo-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: service-mesh-v2
#   labels:
#     app: service-mesh
#     version: v2
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: service-mesh
#       version: v2
#   template:
#     metadata:
#       labels:
#         app: service-mesh
#         version: v2
#     spec:
#       serviceAccountName: sa-service-mesh
#       containers:
#         - env:
#             - name: REACT_APP_TEST
#               value: report-service
#             - name: REACT_APP_THEME
#               value: dark
#           name: service-mesh
#           image: docker.io/cmwylie19/service-mesh:dark
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 3000
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: service-mesh
# spec:
#   host: service-mesh
#   subsets:
#     - name: v1
#       labels:
#         version: v1
#     - name: v2
#       labels:
#         version: v2
