apiVersion: v1
kind: Service
metadata:
  name: service-mesh
  labels:
    app: service-mesh
    service: service-mesh
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: service-mesh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-service-mesh
  labels:
    account: service-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mesh-v1
  labels:
    app: service-mesh
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-mesh
      version: v1
  template:
    metadata:
      labels:
        app: service-mesh
        version: v1
    spec:
      serviceAccountName: bookinfo-service-mesh
      containers:
      - name: service-mesh
        image: docker.io/cmwylie19/service-mesh:light
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000